basePath: /
consumes:
    - application/json
    - application/xml
host: localhost:8080
info:
    license:
        name: MIT
        url: http://opensource.org/licenses/MIT
    title: API.
    version: 0.0.1
paths:
    /getOne/{id}:
        get:
            consumes:
                - application/json
            operationId: getOneRecord
            parameters:
                - description: returns one record
                  format: int
                  in: path
                  name: id
                  required: true
                  type: integer
            produces:
                - application/json
            responses:
                "200":
                    description: ""
                "422":
                    description: ""
            schemes:
                - http
                - https
                - ws
                - wss
            summary: It returns one record.
produces:
    - application/json
schemes:
    - http
    - https
security:
    - api_key: []
securityDefinitions:
    api_key:
        in: header
        name: KEY
        type: apiKey
    oauth2:
        authorizationUrl: /oauth2/auth
        flow: accessCode
        in: header
        scopes:
            bar: foo
        tokenUrl: /oauth2/token
        type: oauth2
swagger: "2.0"
x-meta-array:
    - value1
    - value2
x-meta-array-obj:
    - name: obj
      value: field
x-meta-value: value
